GlobalParameters:
  MinimumRequiredVersion: 4.14.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  NumBenchmarks: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: -1
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 0
  PrintSolutionRejectionReason: True
  DataInitTypeA: 3
  DataInitTypeB: 3
  DataInitTypeC: 3
  DataInitTypeD: 0
  DataInitTypeBeta: 0
  DataInitTypeAlpha: 1
  PrintTensorA: 0
  PrintTensorB: 0
  PrintTensorD: 0
  NewClient: 0

BenchmarkProblems:
  ########################################
  # TN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
      ForkParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
#        - LoopTail: [False]
        - PrefetchLocalRead:  [False]
        - PrefetchGlobalRead: [False]
        - UnrollMajorLDSA: [False]
        - UnrollMajorLDSB: [False]
        - EnableMatrixInstruction : [True]
        - MIBlock:
          - [32, 32, 1, 2, 1, 2]
          - [32, 32, 1, 2, 2, 1]
          - [32, 32, 2, 1, 1, 1]
          - [16, 16, 1, 4, 1, 4]
          - [16, 16, 1, 4, 2, 2]
          - [16, 16, 1, 4, 4, 1]
          - [16, 16, 4, 1, 1, 1]
        - MIWaveGroup:
          - [ 1, 1 ]
          - [ 2, 1 ]
          - [ 1, 2 ]
          - [ 2, 2 ]
          - [ 4, 1 ]
          - [ 1, 4 ]
        - MIWaveTile:
          - [ 1, 1 ]
          - [ 2, 1 ]
          - [ 1, 2 ]
          - [ 2, 2 ]
        - DirectToLds: [True]
        - DirectToLdsInstOffset: [True]
#        - LdsBlockSizePerPad: [256]
        - LdsPadA: [2]
        - LdsPadB: [2]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [8]
        - VectorWidth: [1]
        - GlobalReadVectorWidth: [1]
        - SuppressNoLoadLoop: [False]
        - OptNoLoadLoop: [0]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [256, 3, 272],  [256, 3, 272], [1],  [256, 3, 272]]

########################################
LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"
